"""
Auto-generate YouTube session cookies via Playwright.

These cookies (VISITOR_INFO1_LIVE, CONSENT, etc.) help yt-dlp
avoid "Sign in to confirm you're not a bot" errors.
"""

import asyncio
import logging
import os
import time
from typing import Any

from app.services.browser_service import STEALTH_SCRIPT

logger = logging.getLogger(__name__)

# Paths to try for cookie persistence
COOKIE_PATHS = ["/app/cookies.txt", "/tmp/yt_cookies.txt"]


def _find_writable_cookie_path() -> str | None:
    for path in COOKIE_PATHS:
        dir_name = os.path.dirname(path)
        if os.path.isdir(dir_name) and os.access(dir_name, os.W_OK):
            return path
    return None


def _export_cookies_to_file(cookies: list[dict[str, Any]], path: str) -> None:
    """Write Netscape-format cookies file."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Playwright cookie service",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path_val = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = c.get("expires", 0)
        if expires is None or expires == -1:
            expires = 0
        else:
            expires = int(expires)
        name = c.get("name", "")
        value = c.get("value", "")
        if name and value:
            lines.append(f"{domain}\t{flag}\t{path_val}\t{secure}\t{expires}\t{name}\t{value}")

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    logger.info("Exported %s cookies to %s", len(cookies), path)


class CookieService:
    """Generates fresh YouTube cookies using a headless browser."""

    def __init__(self, timeout: int = 45):
        self.timeout = timeout

    async def generate_youtube_cookies(self) -> str | None:
        """
        Launch Playwright, visit YouTube, handle consent, export cookies.
        Returns the path cookies were written to, or None on failure.
        """
        try:
            from playwright.async_api import async_playwright
        except ImportError:
            logger.error("Playwright not installed")
            return None

        cookie_path = _find_writable_cookie_path()
        if not cookie_path:
            logger.error("No writable cookie path found")
            return None

        logger.info("Generating fresh YouTube cookies...")

        try:
            async with async_playwright() as p:
                browser = await p.chromium.launch(
                    headless=True,
                    args=[
                        "--no-sandbox",
                        "--disable-setuid-sandbox",
                        "--disable-dev-shm-usage",
                        "--disable-accelerated-2d-canvas",
                        "--no-first-run",
                        "--no-zygote",
                        "--disable-gpu",
                        "--disable-blink-features=AutomationControlled",
                        "--disable-infobars",
                        "--window-size=1920,1080",
                        "--disable-extensions",
                        "--disable-default-apps",
                        "--disable-background-networking",
                        "--disable-background-timer-throttling",
                        "--disable-backgrounding-occluded-windows",
                        "--disable-breakpad",
                        "--disable-component-update",
                        "--disable-features=TranslateUI",
                        "--disable-hang-monitor",
                        "--disable-ipc-flooding-protection",
                        "--disable-popup-blocking",
                        "--disable-prompt-on-repost",
                        "--disable-renderer-backgrounding",
                        "--force-color-profile=srgb",
                        "--metrics-recording-only",
                        "--enable-automation",
                        "--password-store=basic",
                        "--use-mock-keychain",
                    ],
                )

                context = await browser.new_context(
                    user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
                    viewport={"width": 1920, "height": 1080},
                    locale="en-US",
                    timezone_id="America/New_York",
                    java_script_enabled=True,
                    bypass_csp=True,
                )

                page = await context.new_page()
                await page.add_init_script(STEALTH_SCRIPT)

                # Step 1: Visit YouTube homepage to get base cookies
                await page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=self.timeout * 1000)
                await asyncio.sleep(4)

                # Handle consent dialog if present (EU/updated ToS)
                consent_selectors = [
                    'button[aria-label="Accept all"]',
                    'button[aria-label="Accept the use of cookies and other data for the purposes described"]',
                    'form[action*="consent.youtube.com"] button',
                    'button:has-text("Accept all")',
                    'button:has-text("I agree")',
                ]
                for selector in consent_selectors:
                    try:
                        btn = await page.query_selector(selector)
                        if btn:
                            await btn.click()
                            logger.info("Clicked consent button: %s", selector)
                            await asyncio.sleep(3)
                            break
                    except Exception:
                        pass

                # Step 2: Visit a popular video to trigger video-specific cookies
                await page.goto("https://www.youtube.com/watch?v=dQw4w9WgXcQ", wait_until="domcontentloaded", timeout=self.timeout * 1000)
                await asyncio.sleep(6)

                # Scroll a bit to trigger lazy-loaded scripts
                await page.evaluate("window.scrollBy(0, 400)")
                await asyncio.sleep(2)

                # Step 3: Export cookies
                cookies = await context.cookies()
                yt_cookies = [c for c in cookies if "youtube" in c.get("domain", "") or "google" in c.get("domain", "")]

                if yt_cookies:
                    _export_cookies_to_file(yt_cookies, cookie_path)
                    logger.info("Generated %s YouTube cookies", len(yt_cookies))
                else:
                    logger.warning("No YouTube cookies found")

                await browser.close()
                return cookie_path if yt_cookies else None

        except Exception as exc:
            logger.exception("Cookie generation failed: %s", exc)
            return None


async def periodic_cookie_refresh(interval_seconds: int = 1800):
    """
    Background task that refreshes cookies every N seconds.
    Default: every 30 minutes.
    """
    service = CookieService()
    while True:
        try:
            await service.generate_youtube_cookies()
        except Exception:
            logger.exception("Periodic cookie refresh failed")
        await asyncio.sleep(interval_seconds)
